apiVersion: v1
kind: Service   # Specifies this as a Service resource
metadata:
  name: {{ .Values.backend.name }}  # Service name, derived from values.yaml
  namespace: default
spec:
  type: {{ .Values.backend.service.type }}  # Type of service (e.g., ClusterIP, NodePort)
  ports:
    - port: {{ .Values.backend.service.port }}  # The port the service operates on
      targetPort: {{ .Values.backend.service.targetPort }}  # The port of the backend container
  selector:
    app: {{ .Values.backend.name }}  # Selector to link service to backend pods