apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storage.size }}
