apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "milestone-2-app.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "milestone-2-app.fullname" . }}
    spec:
      containers:
        - name: frontend-op
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
